### ISSUE TITLE
打包里面少了个依赖mosdns

### ISSUE THREAD

**Issue by dunkeng** [kenzok8/small#111]
root@iStoreOS:~/x86_64# opkg install luci-app-ssr-plus
Unknown package 'luci-app-ssr-plus'.
Collected errors:
 * pkg_hash_check_unresolved: cannot find dependency mosdns for luci-app-ssr-plus
 * pkg_hash_check_unresolved: cannot find dependency yq for luci-app-ssr-plus
 * pkg_hash_check_unresolved: cannot find dependency diffutils for luci-app-ssr-plus
 * pkg_hash_fetch_best_installation_candidate: Packages for luci-app-ssr-plus found, but incompatible with the architectures configured
 * opkg_install_cmd: Cannot install package luci-app-ssr-plus.

少了mosdns，yq/diffutils在官方源是有的

**Comment by EuraGoods** [comment]
我安装也提示了

**Comment by kenzok8** [comment]
[small](https://github.com/kenzok8/small/tree/master/)
 是与 
 [openwrt-packages](https://github.com/kenzok8/openwrt-packages/tree/master/)
  合并使用的
