### ISSUE TITLE
gn应该更新一下了

### ISSUE THREAD

**Issue by ted-zheng** [kenzok8/small#117]
Use c++20 in GN build
不然在ubuntu22.04下可以成功编译，但是在ubuntu23.10下编译会报错。替换为这个就可能通过。[gn](https://gn.googlesource.com/?format=HTML) / [gn.git](https://gn.googlesource.com/gn.git/) / 5fd939de8a66c915778c14a2788a857be858ef6c

**Comment by lirg-111** [comment]
gn
修改makefile
PKG_SOURCE_DATE:=2023-11-17
PKG_SOURCE_VERSION:=7367b0df0a0aa25440303998d54045bda73935a5
PKG_MIRROR_HASH:=c11eb62d257f9e41d29139d66e94d3798b013a650dd493ae8759c57e2e64cfd1
