### ISSUE TITLE
gn报错

### ISSUE THREAD

**Issue by binge8** [kenzok8/small#121]
![屏幕截图 2024-01-25 085212](https://github.com/kenzok8/small/assets/53508344/9e006951-f389-467c-9a5b-bcf5af5451f5)

**Comment by ywt114** [comment]
+1

**Comment by binge8** [comment]
看样子只会无脑搬运，不会修不会适配，再见换库

**Comment by kenzok8** [comment]
我们都有各自的工作与生活，github是兴趣使然，我还搭钱进去租服务器，你若有技术与观点大可以提交或者修复，别一副白吃卡要的感觉，让人心寒！多点包容与建设,才是你应该有的样子！这样无脑喷,是不是更low？

**Comment by binge8** [comment]
不让白嫖可以设为私有。没事换库就完了

**Comment by kenzok8** [comment]
没你想的龌龊

**Comment by kenzok8** [comment]
> 没你想的龌龊

**Comment by yuos-bit** [comment]
> 看样子只会无脑搬运，不会修不会适配，再见换库

you can you up,no can no BB
