### ISSUE TITLE
gn报错

### ISSUE THREAD

**Issue by ywt114** [kenzok8/small#122]
make[3]: Entering directory '/home/runner/work/test/test/openwrt/package/lean/small/gn'
MAKEFLAGS="" /home/runner/work/test/test/openwrt/staging_dir/host/bin/ninja  -j1 -C /home/runner/work/test/test/openwrt/build_dir/hostpkg/gn-2023-11-17-7367b0df/out
ninja: Entering directory `/home/runner/work/test/test/openwrt/build_dir/hostpkg/gn-2023-11-17-7367b0df/out'
[1/287] CXX src/base/command_line.o
FAILED: src/base/command_line.o 
clang++ -MMD -MF src/base/command_line.o.d -I../src -I. -DNDEBUG -O3 -fdata-sections -ffunction-sections -Werror -D_FILE_OFFSET_BITS=64 -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -pthread -pipe -fno-exceptions -fno-rtti -fdiagnostics-color -Wall -Wextra -Wno-unused-parameter -Wextra-semi -Wundef -std=c++17 -Wrange-loop-analysis -Wextra-semi-stmt -c ../src/base/command_line.cc -o src/base/command_line.o
/bin/sh: 1: clang++: not found
ninja: build stopped: subcommand failed.
make[3]: *** [Makefile:58: /home/runner/work/test/test/openwrt/build_dir/hostpkg/gn-2023-11-17-7367b0df/.built] Error 1
make[3]: Leaving directory '/home/runner/work/test/test/openwrt/package/lean/small/gn'
time: package/lean/small/gn/host-compile#0.08#0.04#0.12
    ERROR: package/lean/small/gn [host] failed to build.
make[2]: *** [package/Makefile:114: package/lean/small/gn/host/compile] Error 1
make[2]: Leaving directory '/home/runner/work/test/test/openwrt'
make[1]: *** [package/Makefile:110: /home/runner/work/test/test/openwrt/staging_dir/target-x86_64_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/runner/work/test/test/openwrt'
make: *** [/home/runner/work/test/test/openwrt/include/toplevel.mk:231: world] Error 2
##[error]Process completed with exit code 2.

**Comment by ted-zheng** [comment]
sudo apt install clang

**Comment by kenzok8** [comment]
修复了
