### ISSUE TITLE
luci-app-passwall编译提示xray-core错误，上个月1.2.x版本可以正常编译，请问是否xray-core1.3 版本有问题

### ISSUE THREAD

**Issue by michealhansun** [kenzok8/small#13]
make[2] -C package/small/xray-core compile
    ERROR: package/small/xray-core failed to build.
make -r package/openwrt-packages/luci-app-passwall/compile: build failed. Please re-run make with -j1 V=s or V=sc for a higher verbosity level to see what's going on
/openwrt/include/toplevel.mk:228: recipe for target 'package/openwrt-packages/luci-app-passwall/compile' failed
make: *** [package/openwrt-packages/luci-app-passwall/compile] Error 1

**Comment by michealhansun** [comment]
之前官方的openwrt编译失败
现在换lean的openwrt又可以编译成功了

**Comment by kenzok8** [comment]
最近更新频繁,稍安勿躁！
