### ISSUE TITLE
x-ray编译报错

### ISSUE THREAD

**Issue by authon** [kenzok8/small#131]
make[3] -C package/small/xray-plugin compile
    ERROR: package/small/xray-plugin failed to build.
make -r world: build failed. Please re-run make with -j1 V=s or V=sc for a higher verbosity level to see what's going on
make: *** [/workdir/openwrt/include/toplevel.mk:231: world] Error 1
WARNING: Makefile 'package/kernel/linux/Makefile' has a dependency on 'kmod-video-dma', which does not exist
WARNING: Makefile 'package/kernel/linux/Makefile' has a dependency on 'kmod-video-mem2mem', which does not exist
WARNING: Makefile 'package/kernel/linux/Makefile' has a dependency on 'kmod-video-dma', which does not exist
WARNING: Makefile 'package/small/luci-app-bypass/Makefile' has a dependency on 'lua-maxminddb', which does not exist
make[2]: Entering directory '/workdir/openwrt/scripts/config'
make[2]: 'conf' is up to date.

已填加
rm -rf feeds/packages/lang/golang
git clone https://github.com/sbwml/packages_lang_golang -b 22.x feeds/packages/lang/golang

**Comment by ywt114** [comment]
参考https://github.com/sbwml/openwrt_helloworld/tree/v5

**Comment by authon** [comment]
> 参考https://github.com/sbwml/openwrt_helloworld/tree/v5

感谢，尝试一下

**Comment by kenzok8** [comment]
不用拉取go1.22版本，因为xray已经打了补丁能支持go1.21版本的

**Comment by authon** [comment]
make[3] -C feeds/packages/libs/gperf host-compile
make[3] -C feeds/packages/utils/v2dat compile
ERROR: package/feeds/packages/v2dat failed to build.
make -r world: build failed. Please re-run make with -j1 V=s or V=sc for a higher verbosity level to see what's going on
make: *** [/Ledemaster/openwrt/include/toplevel.mk:231: world] Error 1
make[2]: Entering directory '/Ledemaster/openwrt/scripts/config'
make[2]: 'conf' is up to date.
make[2]: Leaving directory '/Ledemaster/openwrt/scripts/config'
make[1]: Entering directory '/Ledemaster/openwrt'
make[2]: Entering directory '/Ledemaster/openwrt'
make[3]: Entering directory '/Ledemaster/openwrt/target/linux'
make[4]: Entering directory '/Ledemaster/openwrt/target/linux/x86'
请问出现这个又是什么问题.....我翻了一下这个貌似是解压v2ray geoip数据的
