### ISSUE TITLE
redsocks2编译错误

### ISSUE THREAD

**Issue by AndyLin2020** [kenzok8/small#137]
make[4]: Leaving directory '/home/andy/lede/build_dir/target-x86_64_musl/redsocks2-0.67'
touch /home/andy/lede/build_dir/target-x86_64_musl/redsocks2-0.67/.built
rm -rf /home/andy/lede/build_dir/target-x86_64_musl/redsocks2-0.67/.pkgdir/redsocks2.installed /home/andy/lede/build_dir/target-x86_64_musl/redsocks2-0.67/.pkgdir/redsocks2
mkdir -p /home/andy/lede/build_dir/target-x86_64_musl/redsocks2-0.67/.pkgdir/redsocks2
install -d -m0755 /home/andy/lede/build_dir/target-x86_64_musl/redsocks2-0.67/.pkgdir/redsocks2/usr/sbin
install -m0755 /home/andy/lede/build_dir/target-x86_64_musl/redsocks2-0.67/redsocks2 /home/andy/lede/build_dir/target-x86_64_musl/redsocks2-0.67/.pkgdir/redsocks2/usr/sbin
install -d -m0755 /home/andy/lede/build_dir/target-x86_64_musl/redsocks2-0.67/.pkgdir/redsocks2/etc/redsocks2
install -m0644 ./files/redsocks2.template /home/andy/lede/build_dir/target-x86_64_musl/redsocks2-0.67/.pkgdir/redsocks2/etc/redsocks2/config.template
install: cannot stat './files/redsocks2.template': No such file or directory
make[3]: *** [Makefile:55: /home/andy/lede/build_dir/target-x86_64_musl/redsocks2-0.67/.pkgdir/redsocks2.installed] Error 1
make[3]: Leaving directory '/home/andy/lede/feeds/small/redsocks2'
time: package/feeds/small/redsocks2/compile#1.89#0.87#11.28
    ERROR: package/feeds/small/redsocks2 failed to build.
make[2]: *** [package/Makefile:116: package/feeds/small/redsocks2/compile] Error 1
make[2]: Leaving directory '/home/andy/lede'
make[1]: *** [package/Makefile:110: /home/andy/lede/staging_dir/target-x86_64_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/andy/lede'
make: *** [/home/andy/lede/include/toplevel.mk:231：world] 错误 2

**Comment by ohbaby30** [comment]
同错

**Comment by ywt114** [comment]
+1

**Comment by popeyema** [comment]
+1

**Comment by kenzok8** [comment]
先回退到helloword仓库的版本，远程获取的https://github.com/semigodking/redsocks.git 的PKG_SOURCE_VERSION版本有误，尽量去修复

**Comment by popeyema** [comment]
> 先回退到helloword仓库的版本，远程获取的https://github.com/semigodking/redsocks.git 的PKG_SOURCE_VERSION版本有误，尽量去修复

感谢大佬

**Comment by ywt114** [comment]
最近更新bug太多我直接回退到1月9日
cd small/luci-app-passwall
git reset --hard ecd92aa64174f5e7a200678b4122891764a6b245
