### ISSUE TITLE
能否添加libopenssl-legacy相关文件，目前编译时发现shadowsocksr-libev缺少该依赖

### ISSUE THREAD

**Issue by Glunefish** [kenzok8/small#138]
能否添加libopenssl-legacy相关文件，目前编译时发现shadowsocksr-libev缺少该依赖

**Comment by kenzok8** [comment]
libopenssl-legacy 37行里包含了
https://github.com/kenzok8/small/blob/master/shadowsocksr-libev/Makefile

**Comment by Glunefish** [comment]
不知道为什么编译passwall&nbsp; xray-core说缺少这个依赖



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年3月1日(周五) 下午2:40
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [kenzok8/small] 能否添加libopenssl-legacy相关文件，目前编译时发现shadowsocksr-libev缺少该依赖 (Issue #138)




 
libopenssl-legacy 37行里包含了
 https://github.com/kenzok8/small/blob/master/shadowsocksr-libev/Makefile

**Comment by Glunefish** [comment]
看了是包含了，但是还是报错，这是哪里的问题大佬能否告之
WARNING: Makefile 'package/feeds/smpackage/core/Makefile' has a dependency on 'firewall4', which does not exist
WARNING: Makefile 'package/feeds/smpackage/daed-next/Makefile' has a dependency on 'kmod-xdp-sockets-diag', which does not exist
WARNING: Makefile 'package/feeds/smpackage/daed-next/Makefile' has a build dependency on 'bpf-headers', which does not exist
WARNING: Makefile 'package/feeds/smpackage/homeproxy/Makefile' has a dependency on 'firewall4', which does not exist
WARNING: Makefile 'package/feeds/smpackage/luci-app-homeproxy/Makefile' has a dependency on 'firewall4', which does not exist
WARNING: Makefile 'package/feeds/smpackage/luci-app-tencentcloud-cos/Makefile' has a dependency on 'vsftpd-alt', which does not exist
WARNING: Makefile 'package/feeds/smpackage/luci-app-torbp/Makefile' has a dependency on 'obfs4proxy', which does not exist
WARNING: Makefile 'package/feeds/smpackage/openwrt/Makefile' has a dependency on 'libasan', which does not exist
WARNING: Makefile 'package/feeds/packages/prometheus-node-exporter-lua/Makefile' has a dependency on 'bmx6', which does not exist
WARNING: Makefile 'package/feeds/packages/prometheus-node-exporter-lua/Makefile' has a dependency on 'bmx6-json', which does not exist
WARNING: Makefile 'package/feeds/small/shadowsocksr-libev/Makefile' has a dependency on 'libopenssl-legacy', which does not exist
WARNING: Makefile 'package/feeds/small/shadowsocksr-libev/Makefile' has a dependency on 'libopenssl-legacy', which does not exist
WARNING: Makefile 'package/feeds/small/shadowsocksr-libev/Makefile' has a dependency on 'libopenssl-legacy', which does not exist
WARNING: Makefile 'package/feeds/small/shadowsocksr-libev/Makefile' has a dependency on 'libopenssl-legacy', which does not exist
WARNING: Makefile 'package/feeds/small/shadowsocksr-libev/Makefile' has a dependency on 'libopenssl-legacy', which does not exist
 make[1] world
 make[2] tools/compile
 make[2] package/cleanup
 make[3] -C tools/flock compile

**Comment by kenzok8** [comment]
这个报错不影响编译的，你是无法编译还是编译失败了？

**Comment by Glunefish** [comment]
编译passwall 不能通过，就是说缺少这个依赖Makefile 'package/feeds/small/shadowsocksr-libev/Makefile' has a dependency on 'libopenssl-legacy', which does not exist

**Comment by Glunefish** [comment]
feed 源
src-git luci https://github.com/Glunefish/luci-sdf.git;2023
src-git packages https://github.com/Glunefish/packages-sdf.git;2023
src-git routing https://github.com/openwrt/routing.git;openwrt-22.03
src-git telephony https://github.com/openwrt/telephony.git;openwrt-22.03
src-git small https://github.com/kenzok8/small.git;master
src-git smpackage https://github.com/kenzok8/small-package.git;main

**Comment by kenzok8** [comment]
[small-package](https://github.com/kenzok8/small-package.git;main) 这个去掉吧，
如果添加了[small-package](https://github.com/kenzok8/small-package.git;main)就不用再添加small了

**Comment by Glunefish** [comment]
small-package里面插件多些。。。我用得到。。。我再试试编译。。
https://github.com/Glunefish/OPBuild

**Comment by kenzok8** [comment]
small-package 里包含了small的所有插件了，所以不用small再添加了

**Comment by Glunefish** [comment]
哦哦，看反了，哈哈
