### ISSUE TITLE
redsocks2编译错误

### ISSUE THREAD

**Issue by popeyema** [kenzok8/small#139]
ERROR: package/feeds/small/redsocks2 failed to build.
make: *** [/workdir/openwrt/include/toplevel.mk:231: world] Error 1
make -r world: build failed. Please re-run make with -j1 V=s or V=sc for a higher verbosity level to see what's going on
make[2]: Entering directory '/workdir/openwrt/scripts/config'
make[2]: 'conf' is up to date.
make[2]: Leaving directory '/workdir/openwrt/scripts/config'
make[1]: Entering directory '/workdir/openwrt'
make[2]: Entering directory '/workdir/openwrt'
make[3]: Entering directory '/workdir/openwrt/target/linux'
make[4]: Entering directory '/workdir/openwrt/target/linux/rockchip'

**Comment by kenzok8** [comment]
https://github.com/kenzok8/small/issues/137#issuecomment-1972552549
