### ISSUE TITLE
现在编译后几次后,发现passwall里面DNS设置下没有本地DNS了

### ISSUE THREAD

**Issue by wggglggg** [kenzok8/small#15]
现在编译后几次后,发现passwall里面DNS设置下没有本地DNS了, 大家都这样吗?
最新一个月编译了三次左右吧, 确实消失了. 以前编译都有的.

**Comment by la8896** [comment]
> 现在编译后几次后,发现passwall里面DNS设置下没有本地DNS了, 大家都这样吗?
> 最新一个月编译了三次左右吧, 确实消失了. 以前编译都有的.


前一版本passwall 4-15也沒有了
