### ISSUE TITLE
ERROR: package/feeds/packages/v2dat failed to build

### ISSUE THREAD

**Issue by woni928** [kenzok8/small#151]
2024-0312 最新编译 n1云编译
![v2dat](https://github.com/kenzok8/small/assets/28220733/8fbe8282-fd4b-4c43-9e77-76438ca5a464)

**Comment by kenzok8** [comment]
**

> 看上去是v2dat编译出错

**
```yaml
rm -rf feeds/packages/net/{xray*,v2ray*,v2ray*,sing*}
```

**Comment by woni928** [comment]
> **看上去是v2dat编译出错**
> 
> ```yaml
> rm -rf feeds/packages/net/{xray*,v2ray*,v2ray*,sing*}
> ```

感谢k佬。但是没用，还是这个错误，被这个问题折腾三天了都没解决！

**Comment by kenzok8** [comment]
> > **看上去是v2dat编译出错**
> > ```yaml
> > rm -rf feeds/packages/net/{xray*,v2ray*,v2ray*,sing*}
> > ```
> 
> 感谢k佬。但是没用，还是这个错误，被这个问题折腾三天了都没解决！

大概率是源码里面有luci-app-mosdns 包括v2dat ，你仔细看看feeds下面的文件夹

**Comment by woni928** [comment]
> > > **看上去是v2dat编译出错**
> > > ```yaml
> > > rm -rf feeds/packages/net/{xray*,v2ray*,v2ray*,sing*}
> > > ```
> > 
> > 
> > 感谢k佬。但是没用，还是这个错误，被这个问题折腾三天了都没解决！
> 
> 大概率是源码里面有luci-app-mosdns 包括v2dat ，你仔细看看feeds下面的文件夹

谢谢 已经解决
sed -i 's#GO_PKG_TARGET_VARS.*# #g' feeds/packages/utils/v2dat/Makefile

**Comment by NeedforGit** [comment]
> > > > **看上去是v2dat编译出错**
> > > > ```yaml
> > > > rm -rf feeds/packages/net/{xray*,v2ray*,v2ray*,sing*}
> > > > ```
> > > 
> > > 
> > > 感谢k佬。但是没用，还是这个错误，被这个问题折腾三天了都没解决！
> > 
> > 
> > 大概率是源码里面有luci-app-mosdns 包括v2dat ，你仔细看看feeds下面的文件夹
> 
> 谢谢 已经解决 sed -i 's#GO_PKG_TARGET_VARS.*# #g' feeds/packages/utils/v2dat/Makefile

感谢分享！云编译成功！

**Comment by zow2023** [comment]
> > > > **看上去是v2dat编译出错**
> > > > ```yaml
> > > > rm -rf feeds/packages/net/{xray*,v2ray*,v2ray*,sing*}
> > > > ```
> > > 
> > > 
> > > 感谢k佬。但是没用，还是这个错误，被这个问题折腾三天了都没解决！
> > 
> > 
> > 大概率是源码里面有luci-app-mosdns 包括v2dat ，你仔细看看feeds下面的文件夹
> 
> 谢谢 已经解决 sed -i 's#GO_PKG_TARGET_VARS.*# #g' feeds/packages/utils/v2dat/Makefile

朋友 你能指教一下我吗  我用了你的这行命令还是不行
![Uploading Screenshot 2024-03-25 at 18-01-43 Build OpenWrt · zow2023_x-wrt@91c11af.png…]()
