### ISSUE TITLE
xray-core何时恢复？

### ISSUE THREAD

**Issue by yishan2019** [kenzok8/small#152]
编译到[xray-core]出错！何时恢复？

**Comment by qingtian110** [comment]
如果是因为某个插件受限必须要使用go 1.21 的话

你可以考虑使用这个 sbwml 的 xray 包： https://github.com/sbwml/openwrt_helloworld/tree/go1.21/xray-core

以及 xray-plugin  https://github.com/sbwml/openwrt_helloworld/tree/go1.21/xray-plugin


但是不能保证它始终同步更新版本，这个go1.21 兼容版本昨天在某群里问 sbwml 后才刷新版本的 ，但它能直接在 go1.21 版本下直接编译。

**Comment by pangzhaoyhy** [comment]
云编译不知道怎么解决,都是卡在这

**Comment by kenzok8** [comment]
golang要1.22版本，编译才行

**Comment by jerichon** [comment]
重新拉库后，ssr-plus好像消失了？发自我的 iPhone在 2024年3月26日，14:14，有種 ***@***.***> 写道：﻿
golang要1.22版本，编译才行

**Comment by kenzok8** [comment]
#148
