### ISSUE TITLE
ERROR: package/feeds/small/chinadns-ng failed to build.

### ISSUE THREAD

**Issue by XXXstyle** [kenzok8/small#154]
最新的版本2024.03.25和2024.03.27 make download会出现错误，退回到2024.03.07时就没有问题了，请问是我个例问题还是什么。。。寻求帮助，谢谢

**Comment by hgq5** [comment]
我到dl目录下rm -rf chinadns-ng@aarch64-linux-musl@generic+v8a@fast+lto
问题解决
