### ISSUE TITLE
ERROR: package/feeds/packages/shadowsocks-libev failed to build.

### ISSUE THREAD

**Issue by ted-zheng** [kenzok8/small#157]
checking whether ln -s works... yes
checking whether make sets $(MAKE)... (cached) yes
checking for thread local storage (TLS) class... __thread
checking for mbedtls_cipher_setup in -lmbedcrypto... yes
checking whether mbedtls supports Cipher Feedback mode or not... configure: error: MBEDTLS_CIPHER_MODE_CFB required
make[3]: *** [Makefile:130: /home/udb/openwrt/build_dir/target-x86_64_musl/shadowsocks-libev-3.3.5/.configured_68b329da9893e34099c7d8ad5cb9c940] Error 1
make[3]: Leaving directory '/home/udb/openwrt/feeds/packages/net/shadowsocks-libev'
time: package/feeds/packages/shadowsocks-libev/compile#8.19#2.29#11.09
    ERROR: package/feeds/packages/shadowsocks-libev failed to build.
make[2]: *** [package/Makefile:129: package/feeds/packages/shadowsocks-libev/compile] Error 1
make[2]: Leaving directory '/home/udb/openwrt'
make[1]: *** [package/Makefile:123: /home/udb/openwrt/staging_dir/target-x86_64_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/udb/openwrt'
make: *** [/home/udb/openwrt/include/toplevel.mk:233：world] 错误 2

有朋友碰到同样的问题吗？

**Comment by smdx** [comment]
今天编译遇到相同问题
![2024-05-17_121050](https://github.com/kenzok8/small/assets/9279217/20bdd155-7195-48e0-b5be-2779fff07f9f)

**Comment by keke1975** [comment]
2024年5月17日同上！！也遇到了！

**Comment by liulian** [comment]
在第29行 末尾加上 “+libpcre” 就能正常编译了。
见图：
![image](https://github.com/kenzok8/small/assets/1422094/24806597-2f4e-4f76-bcf7-83659147aa8a)

**Comment by Eay5** [comment]
这个问题是不是还没修复?

**Comment by keke1975** [comment]
第29行？？是哪个目录呀？？

**Comment by liulian** [comment]
已经修复了

**Comment by lgs2007m** [comment]
> shadowsocks-libev-3.3.5



> 在第29行 末尾加上 “+libpcre” 就能正常编译了。 见图： ![image](https://private-user-images.githubusercontent.com/1422094/331772252-24806597-2f4e-4f76-bcf7-83659147aa8a.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYyNjcxODMsIm5iZiI6MTcxNjI2Njg4MywicGF0aCI6Ii8xNDIyMDk0LzMzMTc3MjI1Mi0yNDgwNjU5Ny0yZjRlLTRmNzYtYmNmNy04MzY1OTE0N2FhOGEuanBlZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIxVDA0NDgwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJmYmVlNDU2YzUxMDA2MGY1YTIxMDY3YmU1MDUzYTQ1MTYyZWIwYmJkNTA1YTg2MWFlMDkzMmQyMzcxODM5YzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.skLWqgHxarbcHlMw-u99K52R23BoR9Ot8BRWGyjdIEo)
> 
> 现在问题已经修复了

楼主的log中shadowsocks-libev是3.3.5版本，是openwrt仓库里面的版本，你这个图片中应该是kenzok8大佬small仓库的2.5.3版本，不一样哦。我也遇到相同问题，不知删除openwrt仓库的版本只保留small仓库的2.5.3版本行不行。

> 在第29行 末尾加上 “+libpcre” 就能正常编译了。 见图： ![image](https://private-user-images.githubusercontent.com/1422094/331772252-24806597-2f4e-4f76-bcf7-83659147aa8a.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYyNjc1OTIsIm5iZiI6MTcxNjI2NzI5MiwicGF0aCI6Ii8xNDIyMDk0LzMzMTc3MjI1Mi0yNDgwNjU5Ny0yZjRlLTRmNzYtYmNmNy04MzY1OTE0N2FhOGEuanBlZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIxVDA0NTQ1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVjNGZjNzIwZGE4ZjY1MjA4YTQzMTZlODUxNmFmY2MzODg1OGEwYjU0Mzk5NzhkMzM5YmNlMDkzM2VmZGQ5YTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.tukByvhqcczltkV2inLCwcauvqhY7WXFRC7re5hTKes)
> 
> 现在问题已经修复了

楼主的log中shadowsocks-libev版本是3.3.5，是openwrt仓库里面的版本，你这个图片中应该是kenzok8大佬small仓库的2.5.3版本，不一样哦。我也遇到相同问题，不知删除openwrt仓库的版本只保留small仓库的2.5.3版本行不行。

**Comment by ZhangZhang1128** [comment]
6月21 同样遇到此问题
checking whether mbedtls supports Cipher Feedback mode or not... configure: error: MBEDTLS_CIPHER_ODE_CFB required
make[3]: *** [Makefile:130: /home/z/openwrt/build_dir/target-x86_64_musl/shadowsocks-libev-3.3.5/.configured_68b329da9893e34099c7d8ad5cb9c940] Error 1
make[3]: Leaving directory '/home/z/openwrt/feeds/packages/net/shadowsocks-libev'
time: package/feeds/packages/shadowsocks-libev/compile#16.47#1.45#18.85
    ERROR: package/feeds/packages/shadowsocks-libev failed to build.
make[2]: *** [package/Makefile:173: package/feeds/packages/shadowsocks-libev/compile] Error 1
make[2]: Leaving directory '/home/z/openwrt'
make[1]: *** [package/Makefile:167: /home/z/openwrt/staging_dir/target-x86_64_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/z/openwrt'
make: *** [/home/z/openwrt/include/toplevel.mk:248：world] 错误 2
