### ISSUE TITLE
什么原因？

### ISSUE THREAD

**Issue by brianzc0306** [kenzok8/small#17]
Create index file './feeds/small.index' 
grep: feeds/small/Makefile:$(eval: 没有那个文件或目录
grep: $(call: 没有那个文件或目录
grep: BuildPackage,$(PKG_NAME)))/Makefile: 没有那个文件或目录
/home/zhouchao/lede/feeds/small.tmp/info/.files-packageinfo.mk:1: *** 目标模式不含有“%”。 停止。
Collecting target info: done

**Comment by kenzok8** [comment]
rm -rf ./feeds && ./scripts/feeds update -a && ./scripts/feeds install -a && rm -rf ./tmp && make menuconfig

**Comment by mulder125** [comment]
@kenzok8 大佬，你3/8下午更新Makefile后更新已经不会报错，但出现其他问题
