### ISSUE TITLE
使用lean源码添加本项目源编译mosdn没有luci界面

### ISSUE THREAD

**Issue by yanzhx7** [kenzok8/small#171]
使用lean源码添加本项目源编译mosdn没有luci界面，问题原因由于上游作者使用luci2重写UI，不支持lean的lede，只有分支v5-lua支持，请问本项目源可以指定v5-lua分支，或则怎么才能把本项目源里的mosdns回退到v5-lua分支。

**Comment by liuyr88** [comment]
#改用mosdns源码：
rm -rf feeds/luci/applications/luci-app-mosdns
rm -rf feeds/packages/net/v2ray-geodata
git clone https://github.com/sbwml/luci-app-mosdns -b v5-lua package/mosdns
git clone https://github.com/sbwml/v2ray-geodata package/v2ray-geodata
./scripts/feeds install -a

**Comment by yanzhx7** [comment]
> #改用mosdns源码： rm -rf feeds/luci/applications/luci-app-mosdns rm -rf feeds/packages/net/v2ray-geodata git clone https://github.com/sbwml/luci-app-mosdns -b v5-lua package/mosdns git clone https://github.com/sbwml/v2ray-geodata package/v2ray-geodata ./scripts/feeds install -a

这个办法好像不能回退已经添加small软件源，请问已经添加small软件源里的mosdns版本能回退吗？

**Comment by liuyr88** [comment]
lean源码添加kenzok8/small源码编译mosdns没有luci界面，解决方法

git clone https://github.com/coolsnowwolf/lede
cd lede
sed -i '1i src-git kenzo https://github.com/kenzok8/openwrt-packages' feeds.conf.default
sed -i '2i src-git small https://github.com/kenzok8/small' feeds.conf.default
git pull
./scripts/feeds update -a
rm -rf feeds/packages/lang/golang
git clone https://github.com/kenzok8/golang feeds/packages/lang/golang
#改用mosdns源码：
rm -rf feeds/luci/applications/luci-app-mosdns
rm -rf feeds/packages/net/v2ray-geodata
git clone https://github.com/sbwml/luci-app-mosdns -b v5-lua package/mosdns
git clone https://github.com/sbwml/v2ray-geodata package/v2ray-geodata
./scripts/feeds install -a
make menuconfig
make download -j8
make V=s -j$(nproc)
