### ISSUE TITLE
能否将xray core 版本回退？

### ISSUE THREAD

**Issue by ds0tm8340** [kenzok8/small#177]
版本从 升到24.9.30改了一堆的东西，导致和旧版超级多的不兼容，能否回滚到旧版1.8.24 ？

**Comment by kenzok8** [comment]
`PKG_VERSION:=1.8.24
PKG_RELEASE:=1

PKG_SOURCE:=$(PKG_NAME)-$(PKG_VERSION).tar.gz
PKG_SOURCE_URL:=https://codeload.github.com/XTLS/Xray-core/tar.gz/v$(PKG_VERSION)?
PKG_HASH:=86e3e388c77cda4d8457a607356416c201c1f18bbed53f0a9e76a228508ff298`
