### ISSUE TITLE
small里缺少xray-plugin依赖，编译时候会出错失败

### ISSUE THREAD

**Issue by a31663835** [kenzok8/small#29]
ARNING: Makefile 'package/feeds/kenzo/luci-app-vssr/Makefile' has a dependency on 'xray-plugin', which does not exist
编译时选择vssr 勾选了xray，因缺少依赖总是会出错，忘大佬能及时补充。
另外感谢大佬的仓库，很好用很全面，今天偶然发现这种情况。

**Comment by kenzok8** [comment]
前天提交时，误删了，不好意思
