### ISSUE TITLE
feed install的时候缺少upx/host

### ISSUE THREAD

**Issue by adocwang** [kenzok8/small#30]
./scripts/feeds install -a 的时候出现以下输出

WARNING: Makefile 'package/feeds/small/brook/Makefile' has a build dependency on 'upx/host', which does not exist
WARNING: Makefile 'package/feeds/small/hysteria/Makefile' has a build dependency on 'upx/host', which does not exist
WARNING: Makefile 'package/feeds/small/trojan-go/Makefile' has a build dependency on 'upx/host', which does not exist
WARNING: Makefile 'package/feeds/small/v2ray-core/Makefile' has a build dependency on 'upx/host', which does not exist
WARNING: Makefile 'package/feeds/small/v2ray-plugin/Makefile' has a build dependency on 'upx/host', which does not exist
WARNING: Makefile 'package/feeds/small/xray-core/Makefile' has a build dependency on 'upx/host', which does not exist
WARNING: Makefile 'package/feeds/small/xray-plugin/Makefile' has a build dependency on 'upx/host', which does not exist

**Comment by Se7enMuting** [comment]
我也遇到了

**Comment by kenzok8** [comment]
上游仓库xiaorouji 的passwall软件里相比添加了PKG_BUILD_DEPENDS += *****_COMPRESS_UPX:upx/host
而且git说明也表明了
Explicitly depend on host upx
报错不影响编译

**Comment by WYC-2020** [comment]
@Se7enMuting 对的我试过加这个不报错，lede其实已经把upx集成到了tools里面去了，所以可以不用再额外加这个依赖，非要用就用你说的这个，但是记得加-f，而且这个库编译出来的upx比较新
