### ISSUE TITLE
云编译错误信息make[2]: *** [package/Makefile:116: package/feeds/small/xray-core/compile] Error 1

### ISSUE THREAD

**Issue by Django9264** [kenzok8/small#33]
昨天更新了之后云编译错误，前天正常的
![QQ截图20211226123752](https://user-images.githubusercontent.com/82198758/147399002-21748a15-a284-4193-a009-cd01f5fab70a.png)

**Comment by CitrusFlavored** [comment]
同!

**Comment by boshi116** [comment]
一样

**Comment by marsgrace** [comment]
我也是这个错误
