### ISSUE TITLE
编译报错

### ISSUE THREAD

**Issue by Jack-Ywn** [kenzok8/small#34]
**报错日志如下**
![image](https://user-images.githubusercontent.com/72083949/147434657-764acfc0-0576-4a62-81be-c342f188860c.png)

**请问下需要这么解决？谢谢！**

**Comment by kenzok8** [comment]
杨伟能 ***@***.***>于2021年12月27日 周一12:33写道：

> *报错日志如下*
> [image: image]
> <https://user-images.githubusercontent.com/72083949/147434657-764acfc0-0576-4a62-81be-c342f188860c.png>
>
> 请问下需要这么解决？谢谢
>
> 主题argon-lr出错，取消勾选
>

**Comment by Jack-Ywn** [comment]
3Q，取消主题后已经编译成功了
