### ISSUE TITLE
编译passwall，v2ray报错。

### ISSUE THREAD

**Issue by purplestarsky** [kenzok8/small#37]
出错代码如下，我都不知道错在哪里。更换bypass也是v2ray出错，换成SSR，就是xray出错。哪位大神帮看一下。
Makefile:186: recipe for target '/home/super/lede/build_dir/target-x86_64_musl/v2ray-core-4.44.0/.built' failed
make[3]: *** [/home/super/lede/build_dir/target-x86_64_musl/v2ray-core-4.44.0/.built] Error 1
make[3]: Leaving directory '/home/super/lede/feeds/small/v2ray-core'
time: package/feeds/small/v2ray-core/compile#1.05#0.71#1.60
    ERROR: package/feeds/small/v2ray-core failed to build.
package/Makefile:114: recipe for target 'package/feeds/small/v2ray-core/compile' failed
make[2]: *** [package/feeds/small/v2ray-core/compile] Error 1
make[2]: Leaving directory '/home/super/lede'
package/Makefile:110: recipe for target '/home/super/lede/staging_dir/target-x86_64_musl/stamp/.package_compile' failed
make[1]: *** [/home/super/lede/staging_dir/target-x86_64_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/super/lede'
/home/super/lede/include/toplevel.mk:228: recipe for target 'world' failed
make: *** [world] Error 2

**Comment by kenzok8** [comment]
上游同步补丁出错
