### ISSUE TITLE
才更新的pdnsd-alt编译出错

### ISSUE THREAD

**Issue by ghost** [kenzok8/small#39]
<img width="667" alt="image" src="https://user-images.githubusercontent.com/79848219/158168901-ea058bfc-8554-48be-8803-cd61ce478ec7.png">

**Comment by wazzx** [comment]
已经解决了[issue](https://github.com/xiaorouji/openwrt-passwall/issues/1828)
大佬删除一下pdnsd-alt里面的[02-fix-pdnsd-alt-build-error-within-kernel_5.15.patch](https://github.com/kenzok8/small/blob/master/pdnsd-alt/patches/002-fix-pdnsd-alt-build-error-within-kernel_5.15.patch)

**Comment by kenzok8** [comment]
谢谢反馈

**Comment by wazzx** [comment]
> 谢谢反馈
大佬是出了什么问题！导致没有删除掉文件了。你的包太好了。所以想偷懒继续使用，但是昨天这个问题也搞了我差不多一个晚上。。
