### ISSUE TITLE
v2ray-core 编译报错

### ISSUE THREAD

**Issue by 8680** [kenzok8/small#40]
ERROR: package/small/small/v2ray-core failed to build.
make -r world: build failed. Please re-run make with -j1 V=s or V=sc for a higher verbosity level to see what's going on
make: *** [/workdir/openwrt/include/toplevel.mk:230: world] Error 1

**Comment by willie91** [comment]
一样，还以为我编译有问题

**Comment by mebenny** [comment]
刚编译，也一样

**Comment by Luupw3d** [comment]
> ERROR: package/small/small/v2ray-core failed to build. make -r world: build failed. Please re-run make with -j1 V=s or V=sc for a higher verbosity level to see what's going on make: *** [/workdir/openwrt/include/toplevel.mk:230: world] Error 1

该问题解决了吗

**Comment by 8680** [comment]
> > 错误：封装/小型/小型/v2ray-core 无法构建。make -r 世界：构建失败。请使用 -j1 V=s 或 V=sc 重新运行 make 以获得更高的详细级别，以查看发生了什么：*** [/workdir/openwrt/include/toplevel.mk：230：world] 错误 1
> 
> 该问题解决了吗

解决方法
https://github.com/xiaorouji/openwrt-passwall/issues/1874#issuecomment-1091051042
