### ISSUE TITLE
最新v2ray-core-5.0.3编译失败（提示golang问题）

### ISSUE THREAD

**Issue by wazzx** [kenzok8/small#43]
大佬part可能需要更新[issue](https://github.com/xiaorouji/openwrt-passwall/issues/1878)

**Comment by wazzx** [comment]
大佬这[一步](https://github.com/xiaorouji/openwrt-passwall/commit/c9929ec24b53fd608018a0282f9e15a2c2672103)没有操作啊

**Comment by wazzx** [comment]
大佬脚本是不是要更新一下。我感觉有些时候源码文件删除了。这个脚本拷贝过来的时候不会去验证一下

**Comment by kltsao** [comment]
我的问题是v2ray-core/patches/010-go-1.18.patch patch失败

**Comment by wazzx** [comment]
> 我的问题是v2ray-core/patches/010-go-1.18.patch patch失败

源码已经删除，目前不知道为什么同步代码没有删除，你现在自己删除就可以了

**Comment by MikuMaxZ** [comment]
https://github.com/xiaorouji/openwrt-passwall/commit/453e170ac79511238e97285c671850f8d2ee2d1a#diff-780d7d4e1192ef4d96f9026cfb72ab256aab477c86d0776ab2b888a2c3fa6591

**Comment by MikuMaxZ** [comment]
这个修复了

**Comment by wazzx** [comment]
> 这个修复了

这个没有修复。后面是直接移除了的。你可以看一下源码，这边同步没有删除，已经出现2次了

**Comment by MikuMaxZ** [comment]
我去他的库里把v2ray-core复制替换就可以了

**Comment by kenzok8** [comment]
今天同步更新出错，让大家费心了，如果编译失败的
rm -rf ./feeds && ./scripts/feeds update -a && ./scripts/feeds install -a && rm -rf ./tmp && make menuconfig
在跑一次

**Comment by kenzok8** [comment]
现在small是同步fw876 与xiaorouji 包括openwrt官网的最新了

**Comment by wazzx** [comment]
> 现在small是同步fw876 与xiaorouji 包括openwrt官网的最新了

谢谢老大！我非常喜欢老大的脚本，希望老大越来越好
