### ISSUE TITLE
brook依赖md5值要更新

### ISSUE THREAD

**Issue by ligehhh** [kenzok8/small#47]
make[2]: Entering directory '/home/lihh/lede/feeds/small/brook'
mkdir -p /home/lihh/lede/dl
SHELL= flock /home/lihh/lede/tmp/.brook-20220707.tar.gz.flock -c '      /home/lihh/lede/scripts/download.pl "/home/lihh/lede/dl" "brook-20220707.tar.gz" "e054d0c3d0090b2015e9ff5e94a15b452a3e4e1de4588542972cc6c06965537b" "" "https://codeload.github.com/txthinking/brook/tar.gz/v20220707?"    '
+ curl -f --connect-timeout 20 --retry 5 --location --insecure https://codeload.github.com/txthinking/brook/tar.gz/v20220707?/brook-20220707.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  134k  100  134k    0     0  88089      0  0:00:01  0:00:01 --:--:-- 88033
Hash of the downloaded file does not match (file: 377d6be82a8e122cc2e1c87ea10d2f404be6e4cf85304f329b01654e8f551753, requested: e054d0c3d0090b2015e9ff5e94a15b452a3e4e1de4588542972cc6c06965537b) - deleting download.
+ curl -f --connect-timeout 20 --retry 5 --location --insecure https://sources.cdn.openwrt.org/brook-20220707.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404 
Download failed.
+ curl -f --connect-timeout 20 --retry 5 --location --insecure https://sources.openwrt.org/brook-20220707.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
curl: (22) The requested URL returned error: 404 Not Found
Download failed.
+ curl -f --connect-timeout 20 --retry 5 --location --insecure https://mirror2.openwrt.org/sources/brook-20220707.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:02 --:--:--     0
curl: (22) The requested URL returned error: 404 Not Found
Download failed.
No more mirrors to try - giving up.
make[2]: *** [Makefile:45: /home/lihh/lede/dl/brook-20220707.tar.gz] Error 2
make[2]: Leaving directory '/home/lihh/lede/feeds/small/brook'

377d6be82a8e122cc2e1c87ea10d2f404be6e4cf85304f329b01654e8f551753  大佬更新一下

**Comment by kenzok8** [comment]
是的，但是简单的你输入skip也可以
