### ISSUE TITLE
编译brook 20230101版本出错

### ISSUE THREAD

**Issue by mahakalaya** [kenzok8/small#53]
mkdir -p /home/simon/lede/dl
SHELL= flock /home/simon/lede/tmp/.brook-20230101.tar.gz.flock -c '     /home/simon/lede/scripts/download.pl "/home/simon/lede/dl" "brook-20230101.tar.gz" "skip" "" "https://codeload.github.com/txthinking/brook/tar.gz/v20230101?"    '
touch /home/simon/lede/build_dir/target-aarch64_cortex-a53_musl/brook-20230101/.prepared_91a2573fb5f13703f94bb0689259394a_6664517399ebbbc92a37c5bb081b5c53_check
. /home/simon/lede/include/shell.sh; gzip -dc /home/simon/lede/dl/brook-20230101.tar.gz | tar -C /home/simon/lede/build_dir/target-aarch64_cortex-a53_musl/brook-20230101/.. -xf -
[ ! -d ./src/ ] || cp -fpR ./src/. /home/simon/lede/build_dir/target-aarch64_cortex-a53_musl/brook-20230101

Applying ./patches/010-chore-deps-update-iploc-to-fix-build-with-mips.patch using plaintext: 
patching file go.modHunk #1 FAILED at 8.
1 out of 1 hunk FAILED -- saving rejects to file go.mod.rej
patching file go.sum
Hunk #1 FAILED at 10.
1 out of 1 hunk FAILED -- saving rejects to file go.sum.rej
Patch failed!  Please fix ./patches/010-chore-deps-update-iploc-to-fix-build-with-mips.patch!
make[2]: *** [Makefile:51: /home/simon/lede/build_dir/target-aarch64_cortex-a53_musl/brook-20230101/.prepared_91a2573fb5f13703f94bb0689259394a_6664517399ebbbc92a37c5bb081b5c53] Error 1
make[2]: Leaving directory '/home/simon/lede/feeds/small/brook'
time: package/feeds/small/brook/compile#0.18#0.26#0.95
    ERROR: package/feeds/small/brook failed to build.
make[1]: *** [package/Makefile:116: package/feeds/small/brook/compile] Error 1
make[1]: Leaving directory '/home/simon/lede'
make: *** [/home/simon/lede/include/toplevel.mk:231：package/brook/compile] 错误 2

**Comment by mahakalaya** [comment]
删除补丁patches/010-chore-deps-update-iploc-to-fix-build-with-mips.patch后可以编译通过

**Comment by DuCun** [comment]
看了一下，确实`patches/010-chore-deps-update-iploc-to-fix-build-with-mips.patch`补丁在brook`v20230101`版本是多余的
