### ISSUE TITLE
target-x86_64_musl/xray-plugin-1.7.3/.built] Error 1 每次都是这个报错。求各大神帮助

### ISSUE THREAD

**Issue by hwebuse** [kenzok8/small#56]
touch /home/yk/lede/build_dir/target-x86_64_musl/xray-plugin-1.7.3/.configured_1cd727ac7b9ebbe4ee453b5ddb8504b3
rm -f /home/yk/lede/build_dir/target-x86_64_musl/xray-plugin-1.7.3/.built
touch /home/yk/lede/build_dir/target-x86_64_musl/xray-plugin-1.7.3/.built_check
CONFIG_GOLANG_MOD_CACHE_WORLD_READABLE="" GO_BUILD_CACHE_DIR="/home/yk/lede/tmp/go-build" GO_MOD_CACHE_DIR="/home/yk/lede/dl/go-mod-cache" GO_MOD_ARGS="-modcacherw" GO_PKG="github.com/teddysun/xray-plugin" GO_INSTALL_EXTRA="" GO_INSTALL_ALL="" GO_SOURCE_ONLY="" GO_BUILD_PKG="github.com/teddysun/xray-plugin/..." GO_EXCLUDES="" GO_GO_GENERATE="" GO_INSTALL_BIN_PATH="/usr/bin" BUILD_DIR="/home/yk/lede/build_dir/target-x86_64_musl/xray-plugin-1.7.3" GO_BUILD_DIR="/home/yk/lede/build_dir/target-x86_64_musl/xray-plugin-1.7.3/.go_work/build" GO_BUILD_BIN_DIR="/home/yk/lede/build_dir/target-x86_64_musl/xray-plugin-1.7.3/.go_work/build/bin" GO_BUILD_DEPENDS_PATH="/usr/share/gocode" GO_BUILD_DEPENDS_SRC="/home/yk/lede/staging_dir/target-x86_64_musl/usr/share/gocode/src" GOOS="linux" GOARCH="amd64" GO386="" GOAMD64="v1" GOARM="" GOMIPS="" GOMIPS64="" GOPPC64="" CGO_ENABLED=1 CC="x86_64-openwrt-linux-musl-gcc" CXX="x86_64-openwrt-linux-musl-g++" CGO_CFLAGS="-Os -pipe -fno-caller-saves -fno-plt -fhonour-copts -fmacro-prefix-map=/home/yk/lede/build_dir/target-x86_64_musl/xray-plugin-1.7.3=xray-plugin-1.7.3 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro" CGO_CPPFLAGS="-I/home/yk/lede/staging_dir/toolchain-x86_64_gcc-11.3.0_musl/usr/include -I/home/yk/lede/staging_dir/toolchain-x86_64_gcc-11.3.0_musl/include/fortify -I/home/yk/lede/staging_dir/toolchain-x86_64_gcc-11.3.0_musl/include" CGO_CXXFLAGS="-Os -pipe -fno-caller-saves -fno-plt -fhonour-copts -fmacro-prefix-map=/home/yk/lede/build_dir/target-x86_64_musl/xray-plugin-1.7.3=xray-plugin-1.7.3 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro" CGO_LDFLAGS="-L/home/yk/lede/staging_dir/toolchain-x86_64_gcc-11.3.0_musl/usr/lib -L/home/yk/lede/staging_dir/toolchain-x86_64_gcc-11.3.0_musl/lib -znow -zrelro" GOPATH="/home/yk/lede/build_dir/target-x86_64_musl/xray-plugin-1.7.3/.go_work/build" GOCACHE="/home/yk/lede/tmp/go-build" GOMODCACHE="/home/yk/lede/dl/go-mod-cache" GOENV=off /usr/bin/env bash /home/yk/lede/feeds/packages/lang/golang//golang-build.sh build -v -buildvcs=false -trimpath -ldflags "all=-buildid '1675573548' -linkmode external -extldflags '-L/home/yk/lede/staging_dir/toolchain-x86_64_gcc-11.3.0_musl/usr/lib -L/home/yk/lede/staging_dir/toolchain-x86_64_gcc-11.3.0_musl/lib -Wl,-z,now -Wl,-z,relro'"
Finding targets
go: downloading github.com/xtls/xray-core v1.7.3
go: downloading github.com/quic-go/qtls-go1-20 v0.1.0

Building targets
/home/yk/lede/dl/go-mod-cache/github.com/quic-go/qtls-go1-20@v0.1.0/handshake_client.go:11:2: package crypto/ecdh is not in GOROOT (/home/yk/lede/staging_dir/hostpkg/lib/go-cross/src/crypto/ecdh)

make[3]: *** [Makefile:46: /home/yk/lede/build_dir/target-x86_64_musl/xray-plugin-1.7.3/.built] Error 1
make[3]: Leaving directory '/home/yk/lede/feeds/small/xray-plugin'
time: package/feeds/small/xray-plugin/compile#1.36#0.97#2.89
    ERROR: package/feeds/small/xray-plugin failed to build.
make[2]: *** [package/Makefile:116: package/feeds/small/xray-plugin/compile] Error 1
make[2]: Leaving directory '/home/yk/lede'
make[1]: *** [package/Makefile:110: /home/yk/lede/staging_dir/target-x86_64_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/yk/lede'
make: *** [/home/yk/lede/include/toplevel.mk:231：world] 错误 2

**Comment by wggglggg** [comment]
你这个环境。。以前编译成功过吗？可以试试make clean,再rm -rf ./tmp 清清缓存，
再git pull那开始做一次
cd lede
git pull
./scripts/feeds update -a
./scripts/feeds install -a
make defconfig
make download -j8
make V=s -j$(nproc)------以前没成功编译最好这一步替换成单线程方法make V=s -j1。
如果还是失败在老地方，干脆直接删除lede文件夹，从头来一次
git clone https://github.com/coolsnowwolf/lede
cd lede
./scripts/feeds update -a
./scripts/feeds install -a
make menuconfig
make download -j8
make V=s -j1
再不行，就不清楚了

**Comment by hwebuse** [comment]
lede+https://github.com/fw876/helloworld
是可以编译的，但是不喜欢ssrp
想用vssr 但把源换成(https://github.com/kenzok8/openwrt-packages)+/kenzok8/small
编译就会报错

十分谢谢你的回答

**Comment by wggglggg** [comment]
> lede+https://github.com/fw876/helloworld 是可以编译的，但是不喜欢ssrp 想用vssr 但把源换成(https://github.com/kenzok8/openwrt-packages)+/kenzok8/small 编译就会报错
> 
> 十分谢谢你的回答


你说的vssr好像就是helloworld,
因为网址显示  http://192.168.123.1/cgi-bin/luci/admin/services/vssr，就是对应我的OP菜单上的Helloworld,

我的feed文件是这样的，#是让程序忽略那一样，vssr那行前面我给#，另外添加的是helloworld。

src-git packages https://github.com/coolsnowwolf/packages
src-git luci https://github.com/coolsnowwolf/luci
src-git routing https://github.com/coolsnowwolf/routing
src-git telephony https://git.openwrt.org/feed/telephony.git
#src-git video https://github.com/openwrt/video.git
#src-git targets https://github.com/openwrt/targets.git
#src-git oldpackages http://git.openwrt.org/packages.git
#src-link custom /usr/src/openwrt/custom-feed
src-git helloworld https://github.com/fw876/helloworld
src-git small https://github.com/kenzok8/small
src-git kenzo https://github.com/kenzok8/openwrt-packages
#src-git wrtbwmon https://github.com/brvphoenix/luci-app-wrtbwmon
src-git istore https://github.com/linkease/istore
#src-git lua-maxminddb https://github.com/jerrykuku/lua-maxminddb
#src-git vssr https://github.com/jerrykuku/luci-app-vssr
#src-git poweroff https://github.com/esirplayground/luci-app-poweroff

并且make menuconfig时，钩选LuCI-  Applications  -  luci-app-vssr大项后，
下面我钩了  四项，编译是成功的。
Include Xray,
Include Shadowsocks Xray Plugin
Include ShadowsocksR Libev Server
Include Hysteria

**Comment by kenzok8** [comment]
上游升级频繁，而且编译依赖更换了[go1.20.src.tar.gz](https://github.com/kenzok8/small-package/files/10677595/go1.20.src.tar.gz)

**Comment by hwebuse** [comment]
好的，十分感谢您的解答。
