### ISSUE TITLE
hysteria 32位编译不能打开网页

### ISSUE THREAD

**Issue by dfbucy090** [kenzok8/small#61]
用Lede 编译86-32位版本，hysteria 不能科学上网，无法打开网页，去年7月份以前编译的版本都是正常的，大佬能否检查下是哪里问题，64位一直都正常。32位太小众了，盼望大佬关注下。

**Comment by kenzok8** [comment]
你自己的问题

**Comment by dfbucy090** [comment]
> 你自己的问题

是BUG，那边解决了，这边忘记关闭了。https://github.com/apernet/hysteria/issues/583#issuecomment-1469202150

**Comment by kenzok8** [comment]
看到了，我前几天特地编译了32位的，上网没影响，所以认为你的个案
