### ISSUE TITLE
naiveproxy相关编译出错

### ISSUE THREAD

**Issue by hxx006** [kenzok8/small#63]
make[3]: Entering directory '/home/hxx006/lede/feeds/small/naiveproxy'
rm -f /home/hxx006/lede/build_dir/target-x86_64_musl/naiveproxy-113.0.5672.62-1/.built
touch /home/hxx006/lede/build_dir/target-x86_64_musl/naiveproxy-113.0.5672.62-1/.built_check
MAKEFLAGS="" /home/hxx006/lede/staging_dir/host/bin/ninja  -j1 -C "/home/hxx006/lede/build_dir/target-x86_64_musl/naiveproxy-113.0.5672.62-1/src/out/Release" naive
ninja: Entering directory `/home/hxx006/lede/build_dir/target-x86_64_musl/naiveproxy-113.0.5672.62-1/src/out/Release'
ninja: error: loading 'build.ninja': No such file or directory
make[3]: *** [Makefile:116: /home/hxx006/lede/build_dir/target-x86_64_musl/naiveproxy-113.0.5672.62-1/.built] Error 1
make[3]: Leaving directory '/home/hxx006/lede/feeds/small/naiveproxy'
time: package/feeds/small/naiveproxy/compile#0.25#0.05#0.30
    ERROR: package/feeds/small/naiveproxy failed to build.
make[2]: *** [package/Makefile:116: package/feeds/small/naiveproxy/compile] Error 1
make[2]: Leaving directory '/home/hxx006/lede'
make[1]: *** [package/Makefile:110: /home/hxx006/lede/staging_dir/target-x86_64_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/hxx006/lede'
make: *** [/home/hxx006/lede/include/toplevel.mk:231：world] 错误 2

**Comment by kenzok8** [comment]
晚一点修复，后面两个版本与hash拉取有问题，所以回退到上一版本
