### ISSUE TITLE
ip2socks5 Hash of the downloaded file does not match

### ISSUE THREAD

**Issue by freeAhao** [kenzok8/small#64]
`Hash of the downloaded file does not match (file: 5279eb1cb7555cf9292423cc9f672dc43e6e214b3411a6df26a6a1cfa59d88b7, requested: 73a2498dc95934c225d358707e7f7d060b5ce81aa45260ada09cbd15207d27d1) - deleting download.`

**Comment by kenzok8** [comment]
https://github.com/kenzok8/small/commit/04371b7b3a9b5ff158d2aea2553ed24c67120ae6
