### ISSUE TITLE
WARNING: Makefile 'package/feeds/small/sing-box/Makefile' has a dependency on 'kmod-inet-diag', which does not exist

### ISSUE THREAD

**Issue by tedaz** [kenzok8/small#65]
on the latest 'small' code, the command 'make menuconfig' through out error message -
WARNING: Makefile 'package/feeds/small/sing-box/Makefile' has a dependency on 'kmod-inet-diag', which does not exist

**Comment by tedaz** [comment]
the file "small/sing-box/Makefile" line 50 requiring 
	"+kmod-inet-diag"
however this package already removed from the Openwrt source code.
would you please consider remove this line from the file "small/sing-box/Makefile"?

**Comment by kenzok8** [comment]
https://github.com/kenzok8/small/commit/0ea957eea3867085b8270b9cc3750d091de0e05e
