### ISSUE TITLE
ipt2socks md5值需要更新

### ISSUE THREAD

**Issue by ligehhh** [kenzok8/small#66]
SHELL= flock /home/lihh/lede/tmp/.ipt2socks-1.1.3.tar.gz.flock -c '     /home/lihh/lede/scripts/download.pl "/home/lihh/lede/dl" "ipt2socks-1.1.3.tar.gz" "5279eb1cb7555cf9292423cc9f672dc43e6e214b3411a6df26a6a1cfa59d88b7" "" "https://codeload.github.com/zfl9/ipt2socks/tar.gz/v1.1.3?"    '
Hash of the local file ipt2socks-1.1.3.tar.gz does not match (file: 73a2498dc95934c225d358707e7f7d060b5ce81aa45260ada09cbd15207d27d1, requested: 5279eb1cb7555cf9292423cc9f672dc43e6e214b3411a6df26a6a1cfa59d88b7) - deleting download.

**Comment by kenzok8** [comment]
你很久没更新了吧，不是早就修复了吗？
git pull 一下

**Comment by ligehhh** [comment]
已经是最新的了 还是报错

**Comment by SpeedPartner** [comment]
删除`dl`目录中原来已经下载好的`ipt2socks-1.1.3.tar.gz`就可以了
