### ISSUE TITLE
Lienol 22.03 编译出错 .gn_installed] Error 1 大佬大佬看看啥情况

### ISSUE THREAD

**Issue by ferre-han** [kenzok8/small#75]
Applying ./patches/010-gcc.patch using plaintext: 
patching file build/gen.py
touch /home/parallels/openwrt/build_dir/hostpkg/gn-2023-05-05-3dadaf0e/.preparedafce04906220b3ceca3b3dcbf1461060_6664517399ebbbc92a37c5bb081b5c53
python /home/parallels/openwrt/build_dir/hostpkg/gn-2023-05-05-3dadaf0e/build/gen.py --no-last-commit-position
touch /home/parallels/openwrt/build_dir/hostpkg/gn-2023-05-05-3dadaf0e/.configured
C /home/parallels/openwrt/build_dir/hostpkg/gn-2023-05-05-3dadaf0e/out
bash: C: command not found
Makefile:57: recipe for target '/home/parallels/openwrt/build_dir/hostpkg/gn-2023-05-05-3dadaf0e/.built' failed
make[3]: [/home/parallels/openwrt/build_dir/hostpkg/gn-2023-05-05-3dadaf0e/.built] Error 127 (ignored)
touch /home/parallels/openwrt/build_dir/hostpkg/gn-2023-05-05-3dadaf0e/.built
install -d -m0755 /home/parallels/openwrt/staging_dir/hostpkg/bin/
install -m0755 /home/parallels/openwrt/build_dir/hostpkg/gn-2023-05-05-3dadaf0e/out/gn /home/parallels/openwrt/staging_dir/hostpkg/bin/
install: cannot stat '/home/parallels/openwrt/build_dir/hostpkg/gn-2023-05-05-3dadaf0e/out/gn': No such file or directory
Makefile:57: recipe for target '/home/parallels/openwrt/staging_dir/hostpkg/stamp/.gn_installed' failed
make[3]: *** [/home/parallels/openwrt/staging_dir/hostpkg/stamp/.gn_installed] Error 1
make[3]: Leaving directory '/home/parallels/openwrt/feeds/small/gn'
time: package/feeds/small/gn/host-compile#0.26#0.18#0.48
    ERROR: package/feeds/small/gn [host] failed to build.
package/Makefile:118: recipe for target 'package/feeds/small/gn/host/compile' failed
make[2]: *** [package/feeds/small/gn/host/compile] Error 1
make[2]: Leaving directory '/home/parallels/openwrt'
package/Makefile:114: recipe for target '/home/parallels/openwrt/staging_dir/target-mipsel_24kc_musl/stamp/.package_compile' failed
make[1]: *** [/home/parallels/openwrt/staging_dir/target-mipsel_24kc_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/parallels/openwrt'
/home/parallels/openwrt/include/toplevel.mk:228: recipe for target 'world' failed
make: *** [world] Error 2

**Comment by yuos-bit** [comment]
- name: 初始化环境
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo rm -rf /etc/apt/sources.list.d/* /usr/share/dotnet /usr/local/lib/android /opt/ghc
        sudo -E apt-get -qq update
        sudo -E apt-get -qq install ack antlr3 asciidoc autoconf automake autopoint binutils bison build-essential \
        bzip2 ccache cmake cpio curl device-tree-compiler fastjar flex gawk gettext gcc-multilib g++-multilib \
        git gperf haveged help2man intltool libc6-dev-i386 libelf-dev libglib2.0-dev libgmp3-dev libltdl-dev \
        libmpc-dev libmpfr-dev libip4tc2 libncurses5-dev libncursesw5-dev libreadline-dev libssl-dev libtool lrzsz \
        mkisofs msmtp nano ninja-build p7zip p7zip-full patch pkgconf python2.7 python3 python3-pyelftools \
        libpython3-dev qemu-utils rsync scons squashfs-tools subversion swig texinfo uglifyjs upx-ucl unzip \
        vim wget xmlto xxd zlib1g-dev python3-setuptools clang
        sudo add-apt-repository ppa:ubuntu-toolchain-r/test
        sudo add-apt-repository ppa:ubuntu-toolchain-r/ppa
        sudo apt-get install -y gcc-13
        sudo apt-get install -y g++-13
        sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-13 60 --slave /usr/bin/g++ g++ /usr/bin/g++-13
        sudo timedatectl set-timezone "$TZ"
        sudo mkdir -p /workdir
        sudo chown $USER:$GROUPS /workdir
