### ISSUE TITLE
Ubuntu22中xray无法使用Go1.21编译

### ISSUE THREAD

**Issue by XXXstyle** [kenzok8/small#81]
确定已经安装Go1.21，但编译出来的xray依旧是1.20编译的，请问这是哪里出了问题，谢谢。

**Comment by kenzok8** [comment]
我把补丁已经去掉了

**Comment by XXXstyle** [comment]
> 我把补丁已经去掉了

请问是要等待下次更新吗

**Comment by kenzok8** [comment]
不用等，你可以依旧去编译

**Comment by XXXstyle** [comment]
> 不用等，你可以依旧去编译

刚编译出来的还是Go1.2版本的。。。
