### ISSUE TITLE
问一下，passwall和passwall2啥区别啊

### ISSUE THREAD

**Issue by binge8** [kenzok8/small#85]
问一下，passwall和passwall2啥区别啊

**Comment by kenzok8** [comment]
就我个人使用感受
passwall2 分流优、无负载均衡。passwall功能多，有负载均衡等，

**Comment by binge8** [comment]
> 就我个人使用感受 passwall2 分流优、无负载均衡。passwall功能多，有负载均衡等，

大哥你好，初次使用passwall，有个设置不大会，请教一下。局域网内有3个设备固定了IP，怎么设置只能这3个设备可以走代理，其他设备不允许走代理，谢了

**Comment by kenzok8** [comment]
![IMG_4988](https://github.com/kenzok8/small/assets/39034242/6bd8bc59-f4ad-4044-b20d-26bffc8a95ec)
我用ssr截图，大致都差不多，把内网ip确定走代理，确定列表内的才走代理（有些软件叫分流）

**Comment by binge8** [comment]
> ![IMG_4988](https://user-images.githubusercontent.com/39034242/266222554-6bd8bc59-f4ad-4044-b20d-26bffc8a95ec.jpeg) 我用ssr截图，大致都差不多，把内网ip确定走代理，确定列表内的才走代理（有些软件叫分流）

谢谢，这个ssr一目了然，但passwall找半天没搞定，不知道在哪设置
