### ISSUE TITLE
r2s安装报错

### ISSUE THREAD

**Issue by leechaojie** [kenzok8/small#88]
新手，所以不知如何解决

问题如下：
机器是友善的r2s，下载的 aarch64_generic.zip，解压并上传到 tmp 目录
在 tmp 目录内执行 `opkg install *.ipk`，
遇到以下错误:
![image](https://github.com/kenzok8/small/assets/28593271/979d0e2f-99bf-41cc-b214-45ccd4ef3206)

**Comment by kenzok8** [comment]
有些报错不用理会，能正常运行 就行

**Comment by leechaojie** [comment]
> 有些报错不用理会，能正常运行 就行 而且上面运行的命令，是一键全部安装哦，你要知道要安装的是啥 如果你要单独安装ssr plus 应该解压缩后，运行rm -rf {_passwall_,_bypass_,_vssr_} 这个命令的意思就是把passwall 与bypass vssr的安装luci 先删除

谢谢你的回复，重新刷了固件之后仍然报错，然后安装了are-u-ok的passwall2.run，再次执行 `opkg install *.ipk`，虽然除了bypass报错，其他的都安装上了，passwall2也顺利更新到1.20.6了，再次感谢！
