### ISSUE TITLE
官方`quic-go`已经支持`GO1.21`，能不能更新一下brook

### ISSUE THREAD

**Issue by ChaingTsung** [kenzok8/small#93]
![image](https://github.com/kenzok8/small/assets/140521752/34649e58-0e73-4d79-a2df-47047022cf61)

**Comment by lxiaya** [comment]
[010-update-iploc-to-fix-build-for-riscv64.patch](https://github.com/kenzok8/small/files/12798887/010-update-iploc-to-fix-build-for-riscv64.patch)
[020-Bump-quic-go-to-v0.37.6-for-Go-1.21-and-1.20-support.patch](https://github.com/kenzok8/small/files/12798888/020-Bump-quic-go-to-v0.37.6-for-Go-1.21-and-1.20-support.patch)
替换brook/patches文件夹的patch

**Comment by binge8** [comment]
把brook/patches下原来的文件删了，这两个放里面？

> [010-update-iploc-to-fix-build-for-riscv64.patch](https://github.com/kenzok8/small/files/12798887/010-update-iploc-to-fix-build-for-riscv64.patch) [020-Bump-quic-go-to-v0.37.6-for-Go-1.21-and-1.20-support.patch](https://github.com/kenzok8/small/files/12798888/020-Bump-quic-go-to-v0.37.6-for-Go-1.21-and-1.20-support.patch) 替换brook/patches文件夹的patch

**Comment by ChaingTsung** [comment]
> [010-update-iploc-to-fix-build-for-riscv64.patch](https://github.com/kenzok8/small/files/12798887/010-update-iploc-to-fix-build-for-riscv64.patch) [020-Bump-quic-go-to-v0.37.6-for-Go-1.21-and-1.20-support.patch](https://github.com/kenzok8/small/files/12798888/020-Bump-quic-go-to-v0.37.6-for-Go-1.21-and-1.20-support.patch) 替换 brook/patches 文件夹的 patch
直接重新拉取你最新仓库源码应该可以吧
