### ISSUE TITLE
这是怎么回事啊，哪位知道的，请帮忙说一下，谢谢大家了

### ISSUE THREAD

**Issue by hwebuse** [kenzok8/small#94]
Building targets
github.com/quic-go/quic-go/internal/qtls
# github.com/quic-go/quic-go/internal/qtls
/home/yk/lede/dl/go-mod-cache/github.com/quic-go/quic-go@v0.33.0/internal/qtls/go121.go:5:13: cannot use "The version of quic-go you're using can't be built on Go 1.21 yet. For more details, please see https://github.com/quic-go/quic-go/wiki/quic-go-and-Go-versions." (untyped string constant "The version of quic-go you're using can't be built on Go 1.21 yet. F...) as int value in variable declaration

make[3]: *** [Makefile:44: /home/yk/lede/build_dir/target-x86_64_musl/v2ray-plugin-5.7.0/.built] Error 1
make[3]: Leaving directory '/home/yk/lede/feeds/small/v2ray-plugin'
time: package/feeds/small/v2ray-plugin/compile#1.01#1.72#1.32
    ERROR: package/feeds/small/v2ray-plugin failed to build.
make[2]: *** [package/Makefile:116: package/feeds/small/v2ray-plugin/compile] Error 1
make[2]: Leaving directory '/home/yk/lede'
make[1]: *** [package/Makefile:110: /home/yk/lede/staging_dir/target-x86_64_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/yk/lede'
make: *** [/home/yk/lede/include/toplevel.mk:231：world] 错误 2

**Comment by kenzok8** [comment]
不是你的问题，稍晚我修复下

**Comment by binge8** [comment]
> 不是你的问题，稍晚我修复下
> 
> 已修复 [462d2dc](https://github.com/kenzok8/small/commit/462d2dc1c7f43d7b2a527cf182eb905a2c394e7f)

修复不成功
![屏幕截图 2023-10-03 171054](https://github.com/kenzok8/small/assets/53508344/fb745589-c053-4b91-97d1-17a383323037)

**Comment by kenzok8** [comment]
全部清除 重新编译
https://github.com/kenzok8/compile-package/releases 
已能正确编译

**Comment by binge8** [comment]
> 全部清除 重新编译 https://github.com/kenzok8/compile-package/releases 已能正确编译

我是云编译，肯定每次都最新环境，我再试试

**Comment by kenzok8** [comment]
![image](https://github.com/kenzok8/small/assets/39034242/03e68004-48b8-4b7a-82bd-9724c450fdde)

**Comment by binge8** [comment]
> 全部清除 重新编译 https://github.com/kenzok8/compile-package/releases 已能正确编译

还是不行，同样的报错，每次都是最新环境编译，我非常肯定问题还在你这边哈哈

**Comment by dobetter** [comment]
# github.com/quic-go/quic-go/internal/qtls
../../../../../dl/go-mod-cache/github.com/quic-go/quic-go@v0.36.2/internal/qtls/go121.go:5:13: cannot use "The version of quic-go you're using can't be built on Go 1.21 yet. For more details, please see https://github.com/quic-go/quic-go/wiki/quic-go-and-Go-versions." (untyped string constant "The version of quic-go you're using can't be built on Go 1.21 yet. F...) as int value in variable declaration
github.com/AdguardTeam/dnsproxy/proxyutil
github.com/ameshkov/dnscrypt/v2
github.com/AdguardTeam/AdGuardHome/internal/aghhttp
net/http/cookiejar
github.com/AdguardTeam/AdGuardHome/internal/updater
net/http/pprof
golang.org/x/net/http2
github.com/NYTimes/gziphandler
golang.org/x/net/publicsuffix
github.com/AdguardTeam/urlfilter/rules
github.com/AdguardTeam/golibs/pprofutil
github.com/AdguardTeam/urlfilter/filterlist
github.com/AdguardTeam/urlfilter/lookup
github.com/AdguardTeam/urlfilter
github.com/AdguardTeam/AdGuardHome/internal/aghnet
github.com/AdguardTeam/AdGuardHome/internal/whois
github.com/AdguardTeam/AdGuardHome/internal/dhcpd
github.com/AdguardTeam/AdGuardHome/internal/stats
github.com/AdguardTeam/AdGuardHome/internal/filtering
github.com/AdguardTeam/AdGuardHome/internal/client
golang.org/x/net/http2/h2c
github.com/AdguardTeam/AdGuardHome/internal/querylog
github.com/AdguardTeam/AdGuardHome/internal/filtering/safesearch

make[3]: *** [Makefile:78: /home/ubuntu/openwrt/openwrt/build_dir/target-x86_64_musl/adguardhome-0.107.36/.built] Error 1
make[3]: Leaving directory '/home/ubuntu/openwrt/openwrt/feeds/packages/net/adguardhome'
time: package/feeds/packages/adguardhome/compile#167.64#54.63#87.84
    ERROR: package/feeds/packages/adguardhome failed to build.
make[2]: *** [package/Makefile:120: package/feeds/packages/adguardhome/compile] Error 1
make[2]: Leaving directory '/home/ubuntu/openwrt/openwrt'
make[1]: *** [package/Makefile:114: /home/ubuntu/openwrt/openwrt/staging_dir/target-x86_64_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/ubuntu/openwrt/openwrt'
make: *** [/home/ubuntu/openwrt/openwrt/include/toplevel.mk:232: world] Error 2

**Comment by binge8** [comment]
> 不是你的问题，稍晚我修复下
> 
> 已修复 [462d2dc](https://github.com/kenzok8/small/commit/462d2dc1c7f43d7b2a527cf182eb905a2c394e7f)

brook也需要更新啊

**Comment by dobetter** [comment]
> # github.com/quic-go/quic-go/internal/qtls
> 
> ../../../../../dl/go-mod-cache/github.com/quic-go/quic-go@v0.36.2/internal/qtls/go121.go:5:13: cannot use "The version of quic-go you're using can't be built on Go 1.21 yet. For more details, please see https://github.com/quic-go/quic-go/wiki/quic-go-and-Go-versions." (untyped string constant "The version of quic-go you're using can't be built on Go 1.21 yet. F...) as int value in variable declaration
> 
> github.com/AdguardTeam/dnsproxy/proxyutil
> 
> github.com/ameshkov/dnscrypt/v2
> 
> github.com/AdguardTeam/AdGuardHome/internal/aghhttp
> 
> net/http/cookiejar
> 
> github.com/AdguardTeam/AdGuardHome/internal/updater
> 
> net/http/pprof
> 
> golang.org/x/net/http2
> 
> github.com/NYTimes/gziphandler
> 
> golang.org/x/net/publicsuffix
> 
> github.com/AdguardTeam/urlfilter/rules
> 
> github.com/AdguardTeam/golibs/pprofutil
> 
> github.com/AdguardTeam/urlfilter/filterlist
> 
> github.com/AdguardTeam/urlfilter/lookup
> 
> github.com/AdguardTeam/urlfilter
> 
> github.com/AdguardTeam/AdGuardHome/internal/aghnet
> 
> github.com/AdguardTeam/AdGuardHome/internal/whois
> 
> github.com/AdguardTeam/AdGuardHome/internal/dhcpd
> 
> github.com/AdguardTeam/AdGuardHome/internal/stats
> 
> github.com/AdguardTeam/AdGuardHome/internal/filtering
> 
> github.com/AdguardTeam/AdGuardHome/internal/client
> 
> golang.org/x/net/http2/h2c
> 
> github.com/AdguardTeam/AdGuardHome/internal/querylog
> 
> github.com/AdguardTeam/AdGuardHome/internal/filtering/safesearch
> 
> 
> 
> make[3]: *** [Makefile:78: /home/ubuntu/openwrt/openwrt/build_dir/target-x86_64_musl/adguardhome-0.107.36/.built] Error 1
> 
> make[3]: Leaving directory '/home/ubuntu/openwrt/openwrt/feeds/packages/net/adguardhome'
> 
> time: package/feeds/packages/adguardhome/compile#167.64#54.63#87.84
> 
>     ERROR: package/feeds/packages/adguardhome failed to build.
> 
> make[2]: *** [package/Makefile:120: package/feeds/packages/adguardhome/compile] Error 1
> 
> make[2]: Leaving directory '/home/ubuntu/openwrt/openwrt'
> 
> make[1]: *** [package/Makefile:114: /home/ubuntu/openwrt/openwrt/staging_dir/target-x86_64_musl/stamp/.package_compile] Error 2
> 
> make[1]: Leaving directory '/home/ubuntu/openwrt/openwrt'
> 
> make: *** [/home/ubuntu/openwrt/openwrt/include/toplevel.mk:232: world] Error 2

并没有解决。

**Comment by binge8** [comment]
> > # github.com/quic-go/quic-go/internal/qtls
> > ../../../../../dl/go-mod-cache/github.com/quic-go/quic-go@v0.36.2/internal/qtls/go121.go:5:13: cannot use "The version of quic-go you're using can't be built on Go 1.21 yet. For more details, please see https://github.com/quic-go/quic-go/wiki/quic-go-and-Go-versions." (untyped string constant "The version of quic-go you're using can't be built on Go 1.21 yet. F...) as int value in variable declaration
> > github.com/AdguardTeam/dnsproxy/proxyutil
> > github.com/ameshkov/dnscrypt/v2
> > github.com/AdguardTeam/AdGuardHome/internal/aghhttp
> > net/http/cookiejar
> > github.com/AdguardTeam/AdGuardHome/internal/updater
> > net/http/pprof
> > golang.org/x/net/http2
> > github.com/NYTimes/gziphandler
> > golang.org/x/net/publicsuffix
> > github.com/AdguardTeam/urlfilter/rules
> > github.com/AdguardTeam/golibs/pprofutil
> > github.com/AdguardTeam/urlfilter/filterlist
> > github.com/AdguardTeam/urlfilter/lookup
> > github.com/AdguardTeam/urlfilter
> > github.com/AdguardTeam/AdGuardHome/internal/aghnet
> > github.com/AdguardTeam/AdGuardHome/internal/whois
> > github.com/AdguardTeam/AdGuardHome/internal/dhcpd
> > github.com/AdguardTeam/AdGuardHome/internal/stats
> > github.com/AdguardTeam/AdGuardHome/internal/filtering
> > github.com/AdguardTeam/AdGuardHome/internal/client
> > golang.org/x/net/http2/h2c
> > github.com/AdguardTeam/AdGuardHome/internal/querylog
> > github.com/AdguardTeam/AdGuardHome/internal/filtering/safesearch
> > make[3]: *** [Makefile:78: /home/ubuntu/openwrt/openwrt/build_dir/target-x86_64_musl/adguardhome-0.107.36/.built] Error 1
> > make[3]: Leaving directory '/home/ubuntu/openwrt/openwrt/feeds/packages/net/adguardhome'
> > time: package/feeds/packages/adguardhome/compile#167.64#54.63#87.84
> > ```
> > ERROR: package/feeds/packages/adguardhome failed to build.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > make[2]: *** [package/Makefile:120: package/feeds/packages/adguardhome/compile] Error 1
> > make[2]: Leaving directory '/home/ubuntu/openwrt/openwrt'
> > make[1]: *** [package/Makefile:114: /home/ubuntu/openwrt/openwrt/staging_dir/target-x86_64_musl/stamp/.package_compile] Error 2
> > make[1]: Leaving directory '/home/ubuntu/openwrt/openwrt'
> > make: *** [/home/ubuntu/openwrt/openwrt/include/toplevel.mk:232: world] Error 2
> 
> 并没有解决。

现在是真解决了

**Comment by binge8** [comment]
X86没问题了   armv8架构的还是同样报错

**Comment by dobetter** [comment]
> X86没问题了   armv8架构的还是同样报错
你是在ARMV8编译也有问题还是说编译的目标架构是ARMv8的时候有问题？

我是在ARMv8上编译有问题。

**Comment by binge8** [comment]
跟什么平台上编译的关系不大，我是x86上编译armv8有问题

**Comment by dobetter** [comment]
我之前很长时间一直很正常，最近还是相同的配置软件包，编译X86一直出错。

**Comment by binge8** [comment]
> 我之前很长时间一直很正常，最近还是相同的配置软件包，编译X86一直出错。

在什么平台编译的关系不大，就是源码没修复好，x86现在没问题，你清理一下全新编译试试吧

**Comment by dobetter** [comment]
> > 我之前很长时间一直很正常，最近还是相同的配置软件包，编译X86一直出错。
> 
> 
> 
> 在什么平台编译的关系不大，就是源码没修复好，x86现在没问题，你清理一下全新编译试试吧

就是全删了都通不过，只编译最简化配置的可以。

**Comment by authon** [comment]
> X86没问题了 armv8架构的还是同样报错

老哥，x86怎么解决的，我一直提示个版本不对

**Comment by binge8** [comment]
> > X86没问题了 armv8架构的还是同样报错
> 
> 老哥，x86怎么解决的，我一直提示go版本不对

什么也没干正常编译就行，参考参考这个https://github.com/kenzok8/small/issues/95#issue-1925849832

**Comment by dobetter** [comment]
# github.com/quic-go/quic-go/internal/qtls
../../../../../dl/go-mod-cache/github.com/quic-go/quic-go@v0.36.2/internal/qtls/go121.go:5:13: cannot use "The version of quic-go you're using can't be built on Go 1.21 yet. For more details, please see https://github.com/quic-go/quic-go/wiki/quic-go-and-Go-versions." (untyped string constant "The version of quic-go you're using can't be built on Go 1.21 yet. F...) as int value in variable declaration
github.com/AdguardTeam/dnsproxy/proxyutil
github.com/ameshkov/dnscrypt/v2
github.com/AdguardTeam/AdGuardHome/internal/aghhttp
net/http/cookiejar
github.com/AdguardTeam/AdGuardHome/internal/updater
net/http/pprof
golang.org/x/net/http2
github.com/NYTimes/gziphandler
golang.org/x/net/publicsuffix
github.com/AdguardTeam/urlfilter/rules
github.com/AdguardTeam/golibs/pprofutil
github.com/AdguardTeam/urlfilter/filterlist
github.com/AdguardTeam/urlfilter/lookup
github.com/AdguardTeam/urlfilter
github.com/AdguardTeam/AdGuardHome/internal/aghnet
github.com/AdguardTeam/AdGuardHome/internal/whois
github.com/AdguardTeam/AdGuardHome/internal/stats
github.com/AdguardTeam/AdGuardHome/internal/dhcpd
github.com/AdguardTeam/AdGuardHome/internal/filtering
github.com/AdguardTeam/AdGuardHome/internal/client
golang.org/x/net/http2/h2c
github.com/AdguardTeam/AdGuardHome/internal/filtering/safesearch
github.com/AdguardTeam/AdGuardHome/internal/querylog

make[3]: *** [Makefile:78: /home/ubuntu/openwrt/openwrt/build_dir/target-x86_64_musl/adguardhome-0.107.36/.built] Error 1
make[3]: Leaving directory '/home/ubuntu/openwrt/openwrt/feeds/packages/net/adguardhome'
time: package/feeds/packages/adguardhome/compile#166.02#52.72#82.96
    ERROR: package/feeds/packages/adguardhome failed to build.
make[2]: *** [package/Makefile:120: package/feeds/packages/adguardhome/compile] Error 1
make[2]: Leaving directory '/home/ubuntu/openwrt/openwrt'
make[1]: *** [package/Makefile:114: /home/ubuntu/openwrt/openwrt/staging_dir/target-x86_64_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/ubuntu/openwrt/openwrt'
make: *** [/home/ubuntu/openwrt/openwrt/include/toplevel.mk:232: world] Error 2
2
{"ok":true,"result":{"message_id":2678,"from":{"id":392294834,"is_bot":true,"first_name":"\ud83e\udd16\ufe0f\u673a\u5668\u4eba\u64ad\u62a5","username":"dobetterBot"},"

**Comment by binge8** [comment]
github.com/AdguardTeam/AdGuardHome
找这个库去反馈

> # github.com/quic-go/quic-go/internal/qtls
> ../../../../../dl/go-mod-cache/github.com/quic-go/quic-go@v0.36.2/internal/qtls/go121.go:5:13: cannot use "The version of quic-go you're using can't be built on Go 1.21 yet. For more details, please see https://github.com/quic-go/quic-go/wiki/quic-go-and-Go-versions." (untyped string constant "The version of quic-go you're using can't be built on Go 1.21 yet. F...) as int value in variable declaration github.com/AdguardTeam/dnsproxy/proxyutil github.com/ameshkov/dnscrypt/v2 github.com/AdguardTeam/AdGuardHome/internal/aghhttp net/http/cookiejar github.com/AdguardTeam/AdGuardHome/internal/updater net/http/pprof golang.org/x/net/http2 github.com/NYTimes/gziphandler golang.org/x/net/publicsuffix github.com/AdguardTeam/urlfilter/rules github.com/AdguardTeam/golibs/pprofutil github.com/AdguardTeam/urlfilter/filterlist github.com/AdguardTeam/urlfilter/lookup github.com/AdguardTeam/urlfilter github.com/AdguardTeam/AdGuardHome/internal/aghnet github.com/AdguardTeam/AdGuardHome/internal/whois github.com/AdguardTeam/AdGuardHome/internal/stats github.com/AdguardTeam/AdGuardHome/internal/dhcpd github.com/AdguardTeam/AdGuardHome/internal/filtering github.com/AdguardTeam/AdGuardHome/internal/client golang.org/x/net/http2/h2c github.com/AdguardTeam/AdGuardHome/internal/filtering/safesearch github.com/AdguardTeam/AdGuardHome/internal/querylog
> 
> make[3]: *** [Makefile:78: /home/ubuntu/openwrt/openwrt/build_dir/target-x86_64_musl/adguardhome-0.107.36/.built] Error 1 make[3]: Leaving directory '/home/ubuntu/openwrt/openwrt/feeds/packages/net/adguardhome' time: package/feeds/packages/adguardhome/compile#166.02#52.72#82.96 ERROR: package/feeds/packages/adguardhome failed to build. make[2]: *** [package/Makefile:120: package/feeds/packages/adguardhome/compile] Error 1 make[2]: Leaving directory '/home/ubuntu/openwrt/openwrt' make[1]: *** [package/Makefile:114: /home/ubuntu/openwrt/openwrt/staging_dir/target-x86_64_musl/stamp/.package_compile] Error 2 make[1]: Leaving directory '/home/ubuntu/openwrt/openwrt' make: *** [/home/ubuntu/openwrt/openwrt/include/toplevel.mk:232: world] Error 2 2 {"ok":true,"result":{"message_id":2678,"from":{"id":392294834,"is_bot":true,"first_name":"\ud83e\udd16\ufe0f\u673a\u5668\u4eba\u64ad\u62a5","username":"dobetterBot"},"

**Comment by binge8** [comment]
> > X86没问题了 armv8架构的还是同样报错
> 
> 老哥，x86怎么解决的，我一直提示go版本不对

不发出日志谁知道你报什么错
