### ISSUE TITLE
老是出现这个然后编译停止，请教下什么问题。我已经替换提醒的golang

### ISSUE THREAD

**Issue by authon** [kenzok8/small#95]
Building targets
github.com/quic-go/quic-go/internal/qtls
# github.com/quic-go/quic-go/internal/qtls
../../../../../dl/go-mod-cache/github.com/quic-go/quic-go@v0.33.0/internal/qtls/go121.go:5:13: cannot use "The version of quic-go you're using can't be built on Go 1.21 yet. For more details, please see https://github.com/quic-go/quic-go/wiki/quic-go-and-Go-versions." (untyped string constant "The version of quic-go you're using can't be built on Go 1.21 yet. F...) as int value in variable declaration

make[3]: *** [Makefile:43: /workdir/openwrt/build_dir/target-x86_64_musl/v2ray-plugin-5.7.0/.built] Error 1
make[3]: Leaving directory '/workdir/openwrt/feeds/helloworld/v2ray-plugin'
time: package/feeds/helloworld/v2ray-plugin/compile#0.56#0.21#0.61
    ERROR: package/feeds/helloworld/v2ray-plugin failed to build.
make[2]: *** [package/Makefile:116: package/feeds/helloworld/v2ray-plugin/compile] Error 1
make[2]: Leaving directory '/workdir/openwrt'
make[1]: *** [package/Makefile:110: /workdir/openwrt/staging_dir/target-x86_64_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/workdir/openwrt'
make: *** [/workdir/openwrt/include/toplevel.mk:231: world] Error 2
Error: Process completed with exit code 2.

**Comment by authon** [comment]
能否帮忙看看,[action地址](https://github.com/authon/OpenWRT-Action-Group/actions/runs/6403500408/job/17382127443)

**Comment by dobetter** [comment]
一样的错误。

**Comment by kenzok8** [comment]
> v2ray-plugin-5.7.0
你是否是是拉取https://github.com/fw876/helloworld的仓库了？

**Comment by authon** [comment]
> > v2ray-plugin-5.7.0
> > 你是否是是拉取[https://github.com/fw876/helloworld的仓库了？](https://github.com/fw876/helloworld%E7%9A%84%E4%BB%93%E5%BA%93%E4%BA%86%EF%BC%9F)
> > small仓库v2ray-plugin-5.7.0我修复用golang 1.21编译了

是的，那就是不需要拉取fw876的helloworld也能编译SSR和passwall是吧

**Comment by kenzok8** [comment]
> > > v2ray-plugin-5.7.0
> > > 你是否是是拉取[https://github.com/fw876/helloworld的仓库了？](https://github.com/fw876/helloworld%E7%9A%84%E4%BB%93%E5%BA%93%E4%BA%86%EF%BC%9F)
> > > small仓库v2ray-plugin-5.7.0我修复用golang 1.21编译了
> 
> 是的，那就是不需要拉取fw876的helloworld也能编译SSR和passwall是吧

嗯，你用#注释掉，用small仓库试试吧

**Comment by authon** [comment]
> > > > v2ray-plugin-5.7.0
> > > > 你是否是是拉取[https://github.com/fw876/helloworld的仓库了？](https://github.com/fw876/helloworld%E7%9A%84%E4%BB%93%E5%BA%93%E4%BA%86%EF%BC%9F)
> > > > small仓库v2ray-plugin-5.7.0我修复用golang 1.21编译了
> > 
> > 
> > 是的，那就是不需要拉取fw876的helloworld也能编译SSR和passwall是吧
> 
> 嗯，你用#注释掉，用small仓库试试吧，包括xiaorouji的

好的， 现在试试

**Comment by authon** [comment]
> > > > > v2ray-plugin-5.7.0
> > > > > 你是否是是拉取[https://github.com/fw876/helloworld的仓库了？](https://github.com/fw876/helloworld%E7%9A%84%E4%BB%93%E5%BA%93%E4%BA%86%EF%BC%9F)
> > > > > small仓库v2ray-plugin-5.7.0我修复用golang 1.21编译了
> > > 
> > > 
> > > 是的，那就是不需要拉取fw876的helloworld也能编译SSR和passwall是吧
> > 
> > 
> > 嗯，你用#注释掉，用small仓库试试吧，包括xiaorouji的
> 
> 好的， 现在试试

大佬，编译可以走下去了，但是云编译总是超6个小时咋回事😂

**Comment by binge8** [comment]
选的插件太多了，没办法，精简一些吧

> > > > > > v2ray-plugin-5.7.0
> > > > > > 你是否是是拉取[https://github.com/fw876/helloworld的仓库了？](https://github.com/fw876/helloworld%E7%9A%84%E4%BB%93%E5%BA%93%E4%BA%86%EF%BC%9F)
> > > > > > small仓库v2ray-plugin-5.7.0我修复用golang 1.21编译了
> > > > 
> > > > 
> > > > 是的，那就是不需要拉取fw876的helloworld也能编译SSR和passwall是吧
> > > 
> > > 
> > > 嗯，你用#注释掉，用small仓库试试吧，包括xiaorouji的
> > 
> > 
> > 好的， 现在试试
> 
> 大佬，编译可以走下去了，但是云编译总是超6个小时咋回事😂

**Comment by kenzok8** [comment]
> > > > > > v2ray-plugin-5.7.0
> > > > > > 你是否是是拉取[https://github.com/fw876/helloworld的仓库了？](https://github.com/fw876/helloworld%E7%9A%84%E4%BB%93%E5%BA%93%E4%BA%86%EF%BC%9F)
> > > > > > small仓库v2ray-plugin-5.7.0我修复用golang 1.21编译了
> > > > 
> > > > 
> > > > 是的，那就是不需要拉取fw876的helloworld也能编译SSR和passwall是吧
> > > 
> > > 
> > > 嗯，你用#注释掉，用small仓库试试吧，包括xiaorouji的
> > 
> > 
> > 好的， 现在试试
> 
> 大佬，编译可以走下去了，但是云编译总是超6个小时咋回事😂

本地先同样去配置出config文件，跑一次，如果能编译，替换云编译的配置文件，有时插件升级了，但是老的config编译是有冲突的，虽然能成功，但是编译导致出错或者很慢！

**Comment by binge8** [comment]
> > > > > > > v2ray-plugin-5.7.0
> > > > > > > 你是否是是拉取[https://github.com/fw876/helloworld的仓库了？](https://github.com/fw876/helloworld%E7%9A%84%E4%BB%93%E5%BA%93%E4%BA%86%EF%BC%9F)
> > > > > > > small仓库v2ray-plugin-5.7.0我修复用golang 1.21编译了
> > > > > 
> > > > > 
> > > > > 是的，那就是不需要拉取fw876的helloworld也能编译SSR和passwall是吧
> > > > 
> > > > 
> > > > 嗯，你用#注释掉，用small仓库试试吧，包括xiaorouji的
> > > 
> > > 
> > > 好的， 现在试试
> > 
> > 
> > 大佬，编译可以走下去了，但是云编译总是超6个小时咋回事😂
> 
> 本地先同样去配置出config文件，跑一次，如果能编译，替换云编译的配置文件，有时插件升级了，但是老的config编译是有冲突的，虽然能成功，但是编译导致出错或者很慢！

你说的这种可能性并不大，尤其在延长时间方面，前段时间更新的rust尤其突出，光编译这个就要增加近半小时

**Comment by kenzok8** [comment]
😊我的云编译久压根没超过三个小时，一般都是一个半小时至2个小时
