### ISSUE TITLE
sing-box编译失败

### ISSUE THREAD

**Issue by tujj99** [kenzok8/small#96]
Building targets
../../../../../dl/go-mod-cache/github.com/sagernet/cloudflare-tls@v0.0.0-20230829051644-4a68352d0c4a/cfkem.go:25:2: package crypto/ecdh is not in GOROOT (/home/tim/openwrt/staging_dir/hostpkg/lib/go-cross/src/crypto/ecdh)
../../../../../dl/go-mod-cache/github.com/u-root/uio@v0.0.0-20230220225925-ffce2a382923/uio/buffer.go:12:2: no required module provides package github.com/josharian/native; to add it:
        go get github.com/josharian/native

make[3]: *** [Makefile:159: /home/tim/openwrt/build_dir/target-x86_64_musl/sing-box-1.5.2/.built] Error 1
make[3]: Leaving directory '/home/tim/openwrt/feeds/small/sing-box'
time: package/feeds/small/sing-box/compile#0.63#0.91#1.75
    ERROR: package/feeds/small/sing-box failed to build.
make[2]: *** [package/Makefile:120: package/feeds/small/sing-box/compile] Error 1
make[2]: Leaving directory '/home/tim/openwrt'
make[1]: *** [package/Makefile:114: /home/tim/openwrt/staging_dir/target-x86_64_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/tim/openwrt'
make: *** [/home/tim/openwrt/include/toplevel.mk:230: world] Error 2

make menuconfig手工取消passwall/passwall2以及sing-box/v2ray-plugin以后编译通过

**Comment by xiaojing110** [comment]
更新到1.5.3或者1.6.0beta1
